// Shared flat ESLint config for every TypeScript package in the repo. Written in TypeScript —
// ESLint >=10 loads `eslint.config.ts` directly via its bundled `jiti`, so no extra dependency is
// needed (on ESLint 9, add `jiti` as a devDependency). The config file lints itself, so keep it clean.
//
// Intentionally NOT type-aware (no parserOptions.project): linting stays fast and needs only the
// root install — it does not need each package's own node_modules to resolve plugins. No React in
// this repo (no .tsx), so the React block from the template is omitted.
import eslint from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import unusedImports from 'eslint-plugin-unused-imports';
import tseslint from 'typescript-eslint';
import globals from 'globals';

export default defineConfig([
  globalIgnores([
    '**/node_modules/**',
    '**/dist/**',
    '**/build/**',
    // Generated by kysely-codegen — never hand-formatted (mirror in .prettierignore).
    '**/lib/db/codegen.d.ts',
  ]),
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Node globals across the repo (process, console, …).
    languageOptions: { globals: { ...globals.node } },
    plugins: { 'unused-imports': unusedImports },
    rules: {
      'unused-imports/no-unused-imports': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports', disallowTypeAnnotations: false },
      ],
      '@typescript-eslint/no-import-type-side-effects': 'error',
      '@typescript-eslint/consistent-type-definitions': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
    },
  },
  {
    files: ['**/*.{spec,test}.{ts,tsx}'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },
  {
    files: ['**/*.d.ts'],
    rules: {
      'unused-imports/no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    // NestJS relies on runtime dependency injection: a class referenced only as a constructor
    // parameter type (an injected service) must stay a VALUE import so `emitDecoratorMetadata` can
    // emit it — `import type` would elide it and break DI. `consistent-type-imports` can't tell those
    // apart from real type-only imports, so it's off for the Nest app.
    files: ['projects/tx-payees/**/*.ts'],
    rules: { '@typescript-eslint/consistent-type-imports': 'off' },
  },
  // Prettier LAST: eslint-plugin-prettier/recommended runs Prettier as the `prettier/prettier` rule
  // and disables ESLint's conflicting formatting rules, so the two never fight.
  prettierRecommended,
  {
    // AFTER prettier, on purpose. eslint-config-prettier (bundled into prettierRecommended) treats
    // `curly` as a "special rule" and force-disables it, because `curly: multi-line`/`multi-or-nest`
    // can fight Prettier's line breaking. `curly: all` does NOT conflict — Prettier never strips
    // braces — so we re-enable it here. Put this block before prettierRecommended and the rule
    // silently resolves to severity 0: configured, but never firing.
    rules: { curly: ['error', 'all'] },
  },
]);
