service: scrape-txs-scheduled-lambda
frameworkVersion: '3'

provider:
  name: aws

functions:
  cronHandler:
    image: ${env:ECR_REPO_URL}:${env:IMAGE_TAG}
    memorySize: 1024
    timeout: 300 # 5 minutes
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
    events:
      # Invoke Lambda function every day at 7am Guatemala time
      - schedule:
          method: scheduler # use AWS::Scheduler::Schedule (EventBridge rule) instead of AWS::Events::Rule (CloudWatch Events rule)
          rate: cron(0 7 * * ? *)
          timezone: America/Guatemala # possible with AWS::Scheduler::Schedule
