/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPayeesRouteImport } from './routes/_app/payees'
import { Route as AppSpendingRouteImport } from './routes/_app/spending'
import { Route as AppUnmatchedRouteImport } from './routes/_app/unmatched'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts/$accountId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayeesRoute = AppPayeesRouteImport.update({
  id: '/payees',
  path: '/payees',
  getParentRoute: () => AppRoute,
} as any)
const AppSpendingRoute = AppSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AppRoute,
} as any)
const AppUnmatchedRoute = AppUnmatchedRouteImport.update({
  id: '/unmatched',
  path: '/unmatched',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/payees': typeof AppPayeesRoute
  '/spending': typeof AppSpendingRoute
  '/unmatched': typeof AppUnmatchedRoute
  '/api/health': typeof ApiHealthRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts/': typeof AppAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/payees': typeof AppPayeesRoute
  '/spending': typeof AppSpendingRoute
  '/unmatched': typeof AppUnmatchedRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AppIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts': typeof AppAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/payees': typeof AppPayeesRoute
  '/_app/spending': typeof AppSpendingRoute
  '/_app/unmatched': typeof AppUnmatchedRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payees'
    | '/spending'
    | '/unmatched'
    | '/api/health'
    | '/accounts/$accountId'
    | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/payees'
    | '/spending'
    | '/unmatched'
    | '/api/health'
    | '/'
    | '/accounts/$accountId'
    | '/accounts'
  id:
    | '__root__'
    | '/_app'
    | '/_app/payees'
    | '/_app/spending'
    | '/_app/unmatched'
    | '/api/health'
    | '/_app/'
    | '/_app/accounts/$accountId'
    | '/_app/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payees': {
      id: '/_app/payees'
      path: '/payees'
      fullPath: '/payees'
      preLoaderRoute: typeof AppPayeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spending': {
      id: '/_app/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof AppSpendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unmatched': {
      id: '/_app/unmatched'
      path: '/unmatched'
      fullPath: '/unmatched'
      preLoaderRoute: typeof AppUnmatchedRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPayeesRoute: typeof AppPayeesRoute
  AppSpendingRoute: typeof AppSpendingRoute
  AppUnmatchedRoute: typeof AppUnmatchedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPayeesRoute: AppPayeesRoute,
  AppSpendingRoute: AppSpendingRoute,
  AppUnmatchedRoute: AppUnmatchedRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
