CREATE TABLE "bank_txs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bank_txs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"bank_key" text NOT NULL,
	"account_number" text NOT NULL,
	"month" text NOT NULL,
	"date" date NOT NULL,
	"doc_no" text NOT NULL,
	"description" text NOT NULL,
	"amount" numeric NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "bank_txs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "config" (
	"id" text PRIMARY KEY NOT NULL,
	"data" json NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE UNIQUE INDEX "bank_txs_unique_cols" ON "bank_txs" USING btree ("bank_key","account_number","date","doc_no","description","amount");