service: scrape-txs-scheduled
frameworkVersion: '3'

provider:
  name: aws
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    MAILER_SMTP_ACCOUNT: ${env:MAILER_SMTP_ACCOUNT}
    MAILER_SMTP_PASSWORD: ${env:MAILER_SMTP_PASSWORD}
    MAILER_ME: ${env:MAILER_ME}
    PLAYWRIGHT_TRACES_S3_BUCKET_ID: ${env:PLAYWRIGHT_TRACES_S3_BUCKET_ID}

functions:
  bancoIndustrialGtHandler:
    image: ${env:ECR_REPO_URL}:${env:IMAGE_TAG}
    memorySize: 1024
    timeout: 300 # 5 minutes
    environment:
      BANK_KEY: bancoIndustrialGt
    role: ${env:LAMBDA_ROLE_ARN}
    events:
      # Invoke Lambda function every day at 7am Guatemala time
      - schedule:
          method: scheduler # use AWS::Scheduler::Schedule (EventBridge rule) instead of AWS::Events::Rule (CloudWatch Events rule)
          rate: cron(0 7 * * ? *)
          timezone: America/Guatemala # possible with AWS::Scheduler::Schedule
  bacGtHandler:
    image: ${env:ECR_REPO_URL}:${env:IMAGE_TAG}
    memorySize: 1024
    timeout: 300 # 5 minutes
    environment:
      BANK_KEY: bacGt
    role: ${env:LAMBDA_ROLE_ARN}
    events:
      # Invoke Lambda function every day at 7am Guatemala time
      - schedule:
          method: scheduler # use AWS::Scheduler::Schedule (EventBridge rule) instead of AWS::Events::Rule (CloudWatch Events rule)
          rate: cron(0 7 * * ? *)
          timezone: America/Guatemala # possible with AWS::Scheduler::Schedule
  bacCrHandler:
    image: ${env:ECR_REPO_URL}:${env:IMAGE_TAG}
    memorySize: 1024
    timeout: 300 # 5 minutes
    environment:
      BANK_KEY: bacCr
    role: ${env:LAMBDA_ROLE_ARN}
    events:
      # Invoke Lambda function every day at 7am Guatemala time
      - schedule:
          method: scheduler # use AWS::Scheduler::Schedule (EventBridge rule) instead of AWS::Events::Rule (CloudWatch Events rule)
          rate: cron(0 7 * * ? *)
          timezone: America/Guatemala # possible with AWS::Scheduler::Schedule
