create table "public"."banco_industrial_gt_txs" (
    "id" bigint generated by default as identity not null,
    "month" text not null,
    "date" date not null,
    "description" text not null,
    "doc_no" text not null,
    "amount" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."banco_industrial_gt_txs" enable row level security;

CREATE UNIQUE INDEX banco_industrial_gt_txs_pkey ON public.banco_industrial_gt_txs USING btree (id);

alter table "public"."banco_industrial_gt_txs" add constraint "banco_industrial_gt_txs_pkey" PRIMARY KEY using index "banco_industrial_gt_txs_pkey";

grant delete on table "public"."banco_industrial_gt_txs" to "anon";

grant insert on table "public"."banco_industrial_gt_txs" to "anon";

grant references on table "public"."banco_industrial_gt_txs" to "anon";

grant select on table "public"."banco_industrial_gt_txs" to "anon";

grant trigger on table "public"."banco_industrial_gt_txs" to "anon";

grant truncate on table "public"."banco_industrial_gt_txs" to "anon";

grant update on table "public"."banco_industrial_gt_txs" to "anon";

grant delete on table "public"."banco_industrial_gt_txs" to "authenticated";

grant insert on table "public"."banco_industrial_gt_txs" to "authenticated";

grant references on table "public"."banco_industrial_gt_txs" to "authenticated";

grant select on table "public"."banco_industrial_gt_txs" to "authenticated";

grant trigger on table "public"."banco_industrial_gt_txs" to "authenticated";

grant truncate on table "public"."banco_industrial_gt_txs" to "authenticated";

grant update on table "public"."banco_industrial_gt_txs" to "authenticated";

grant delete on table "public"."banco_industrial_gt_txs" to "service_role";

grant insert on table "public"."banco_industrial_gt_txs" to "service_role";

grant references on table "public"."banco_industrial_gt_txs" to "service_role";

grant select on table "public"."banco_industrial_gt_txs" to "service_role";

grant trigger on table "public"."banco_industrial_gt_txs" to "service_role";

grant truncate on table "public"."banco_industrial_gt_txs" to "service_role";

grant update on table "public"."banco_industrial_gt_txs" to "service_role";


