revoke delete on table "public"."banco_industrial_gt_txs" from "anon";

revoke insert on table "public"."banco_industrial_gt_txs" from "anon";

revoke references on table "public"."banco_industrial_gt_txs" from "anon";

revoke select on table "public"."banco_industrial_gt_txs" from "anon";

revoke trigger on table "public"."banco_industrial_gt_txs" from "anon";

revoke truncate on table "public"."banco_industrial_gt_txs" from "anon";

revoke update on table "public"."banco_industrial_gt_txs" from "anon";

revoke delete on table "public"."banco_industrial_gt_txs" from "authenticated";

revoke insert on table "public"."banco_industrial_gt_txs" from "authenticated";

revoke references on table "public"."banco_industrial_gt_txs" from "authenticated";

revoke select on table "public"."banco_industrial_gt_txs" from "authenticated";

revoke trigger on table "public"."banco_industrial_gt_txs" from "authenticated";

revoke truncate on table "public"."banco_industrial_gt_txs" from "authenticated";

revoke update on table "public"."banco_industrial_gt_txs" from "authenticated";

revoke delete on table "public"."banco_industrial_gt_txs" from "service_role";

revoke insert on table "public"."banco_industrial_gt_txs" from "service_role";

revoke references on table "public"."banco_industrial_gt_txs" from "service_role";

revoke select on table "public"."banco_industrial_gt_txs" from "service_role";

revoke trigger on table "public"."banco_industrial_gt_txs" from "service_role";

revoke truncate on table "public"."banco_industrial_gt_txs" from "service_role";

revoke update on table "public"."banco_industrial_gt_txs" from "service_role";

alter table "public"."banco_industrial_gt_txs" drop constraint "banco_industrial_gt_txs_pkey";

drop index if exists "public"."banco_industrial_gt_txs_account_number_month_date_descripti_idx";

drop index if exists "public"."banco_industrial_gt_txs_pkey";

drop table "public"."banco_industrial_gt_txs";

create table "public"."bank_txs" (
    "id" bigint generated by default as identity not null,
    "month" text not null,
    "date" date not null,
    "description" text not null,
    "doc_no" text not null,
    "amount" numeric not null,
    "created_at" timestamp with time zone not null default now(),
    "account_number" text not null,
    "bank_key" text not null,
    "tx_key" text not null
);


alter table "public"."bank_txs" enable row level security;

CREATE UNIQUE INDEX banco_industrial_gt_txs_account_number_month_date_descripti_idx ON public.bank_txs USING btree (account_number, month, date, description, doc_no, amount);

CREATE UNIQUE INDEX banco_industrial_gt_txs_pkey ON public.bank_txs USING btree (id);

alter table "public"."bank_txs" add constraint "banco_industrial_gt_txs_pkey" PRIMARY KEY using index "banco_industrial_gt_txs_pkey";

grant delete on table "public"."bank_txs" to "anon";

grant insert on table "public"."bank_txs" to "anon";

grant references on table "public"."bank_txs" to "anon";

grant select on table "public"."bank_txs" to "anon";

grant trigger on table "public"."bank_txs" to "anon";

grant truncate on table "public"."bank_txs" to "anon";

grant update on table "public"."bank_txs" to "anon";

grant delete on table "public"."bank_txs" to "authenticated";

grant insert on table "public"."bank_txs" to "authenticated";

grant references on table "public"."bank_txs" to "authenticated";

grant select on table "public"."bank_txs" to "authenticated";

grant trigger on table "public"."bank_txs" to "authenticated";

grant truncate on table "public"."bank_txs" to "authenticated";

grant update on table "public"."bank_txs" to "authenticated";

grant delete on table "public"."bank_txs" to "service_role";

grant insert on table "public"."bank_txs" to "service_role";

grant references on table "public"."bank_txs" to "service_role";

grant select on table "public"."bank_txs" to "service_role";

grant trigger on table "public"."bank_txs" to "service_role";

grant truncate on table "public"."bank_txs" to "service_role";

grant update on table "public"."bank_txs" to "service_role";


